version: "2.4"
services:
    node:
        build: .
        ports: [3000:3000]
        command: nodemon
        environment:
            - PORT=3000
            - HOST=localhost:3000
        volumes:
            - ./:/usr/src/app/
