version: "2.4"
services:
    node:
        image: humaidk2/node-simple
        ports: [8080:8080]
        command: nodemon
        environment:
            - PORT=8080
            - HOST=localhost:8080
        volumes:
            - ./:/usr/src/app/
