version: "2.4"
services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports: [8080:8080]
        command: nodemon
        environment:
            - PORT=8080
            - HOST=localhost:8080
        volumes:
            - ./:/usr/src/app/
    nextjs:
        build:
            context: project-front
            dockerfile: Dockerfile
        ports: [3000:3000]
        environment:
            - PORT=3000
            - HOST=localhost:3000
        volumes:
            - ./project-front:/usr/src/app/front
            - /usr/src/app/front/node_modules
            - /usr/src/app/front/.next
