version: "2.4"
services:
    node:
        image: humaidk2/node-simple
        ports: [80:3000]
        command: nodemon
        environment:
            - PORT=3000
            - HOST=localhost:3000
        volumes:
            - ./:/usr/src/app/
